---

- include: _nginx_ppa.yml
  when: nginx_use_ppa

- name: nginx is installed
  apt:
    force: yes
    update_cache: yes
    cache_valid_time: 3600
    name: nginx
    state: latest
  register: _nginx_install

- stat:
    path: "{{ ssl_dh_file }}"
  register: _dh_file_st

- name: Diffie-Hellman parameter is generated
  shell: /usr/bin/openssl dhparam -out "{{ ssl_dh_file }}" {{ ssl_dh_size }}
  args:
    chdir:
  when: (encryption != "off") and not _dh_file_st.stat.exists

- include: _configure_nginx_apache_style.yml

- name: nginx default site is disabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_disable_default_site
  notify: reload nginx

- name: php is installed
  apt:
    name: php5-fpm
    state: latest
  when: features.php is defined

- name: nginx vhost is configured
  template: 
    src: "nginx-site.conf.j2"
    dest: /etc/nginx/sites-available/{{site_name}}.conf
    owner: root 
    mode: '0644'
  register: nginx_vhost_config_template
  notify: reload nginx

- name: nginx vhost is enabled
  file:
    src: "/etc/nginx/sites-available/{{site_name}}.conf"
    dest: "/etc/nginx/sites-enabled/{{site_name}}.conf"
    state: link
    owner: root
    mode: '0644'
  notify: reload nginx

- stat:
    path: /bin/systemctl
  register: _systemctl_executable

- name: nginx service is unmasked
  command: /bin/systemctl unmask nginx
  when: _nginx_install.changed and _systemctl_executable.stat.exists

- name: nginx service is enabled
  service:
    name: nginx
    enabled: true
